# Generated by Django 5.1.2 on 2024-10-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTransactionSummary',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField()),
                ('total_transactions', models.IntegerField()),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gained', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'client_transaction_summary',
                'managed': False,
            },
        ),
    ]
